[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
postcard = { version = "1.1.1", features = ["use-std"] }
serde = "1.0.217"
tokio = "1.43.0"
tokio-tungstenite = "0.26.1"
